import type { JobRole } from '@/types/courses';

export const MOCK_JOB_ROLES: JobRole[] = [
  { id: 1, name: 'Warehouse Manager', assignedCompanies: 'Lean Logistics, OSHA Compliance, Delta Warehousing, SafeMove Solutions, Efficient Storage Co.', status: true },
  { id: 2, name: 'Quality Control Inspector', assignedCompanies: 'ISO 9001, Quality Assurance Corp., Precision Inspection, SafeGuard Services, Quality First Inc.', status: true },
  { id: 3, name: 'Logistics Coordinator', assignedCompanies: 'Supply Chain Management, Freight Solutions, Cargo Masters, TransportSafe, Logistics Pro', status: true },
  { id: 4, name: 'Safety Manager', assignedCompanies: 'Risk Assessment, Safety First Inc., Compliance Experts, Secure Workplaces, HealthGuard Solutions', status: true },
  { id: 5, name: 'Production Supervisor', assignedCompanies: 'Lean Manufacturing, Efficiency Experts, Safety Protocols, Streamline Inc., WorkSafe Solutions', status: true },
  { id: 6, name: 'Environmental Technician', assignedCompanies: 'Environmental Safety, Eco Solutions, Compliance Services, GreenPath, Safe Environment Co.', status: true },
  { id: 7, name: 'Operations Analyst', assignedCompanies: 'Data Analysis, Process Improvement, Efficiency Experts, Optimized Operations, Insight Solutions', status: true },
  { id: 8, name: 'Compliance Officer', assignedCompanies: 'Regulatory Compliance, Legal Standards Inc., Policy Experts, SafeTrack, Compliance First', status: false },
  { id: 9, name: 'Maintenance Technician', assignedCompanies: 'ProFix Solutions, Equipment Care, Industrial Maintenance, TechRepair, Asset Guard', status: true },
  { id: 10, name: 'Health & Safety Advisor', assignedCompanies: 'Wellness Corp., SafeWork Advisors, Health Protocols, Shield Safety, Workplace Wellness', status: true },
  { id: 11, name: 'Procurement Specialist', assignedCompanies: 'BuyRight Corp., Vendor Management, SupplyChain Direct, ProcurePro', status: true },
  { id: 12, name: 'Training Coordinator', assignedCompanies: 'LearnHub, SkillBridge, Development Corp., TrainSmart Inc.', status: true },
  { id: 13, name: 'Forklift Operator', assignedCompanies: 'Heavy Lift Inc., Warehouse Ops, SafeLift Solutions, LoadMaster, Industrial Movers', status: true },
  { id: 14, name: 'Site Supervisor', assignedCompanies: 'BuildRight Co., Construction Safety, SiteGuard, On-Site Solutions', status: false },
  { id: 15, name: 'HR Generalist', assignedCompanies: 'PeopleCare, Talent Solutions, HR Excellence, WorkForce Pro, Employee First', status: true },
  { id: 16, name: 'Plant Manager', assignedCompanies: 'Manufacturing Hub, Efficiency Corp., Process Leaders, PlantPro Inc.', status: true },
  { id: 17, name: 'Fleet Coordinator', assignedCompanies: 'TransitFleet, Vehicle Management, Route Planner, FleetSafe, DriveRight', status: true },
  { id: 18, name: 'Lab Technician', assignedCompanies: 'LabSafe Inc., Testing Solutions, Precision Lab, QualityTest Corp.', status: true },
  { id: 19, name: 'Electrical Supervisor', assignedCompanies: 'PowerSafe, ElectroPro, Wiring Solutions, VoltGuard, CircuitSafe', status: true },
  { id: 20, name: 'Emergency Response Lead', assignedCompanies: 'CrisisManagement, FirstResponse Corp., EmergencyPro, SafetyNet', status: true },
  { id: 21, name: 'Waste Management Specialist', assignedCompanies: 'EcoWaste, Disposal Solutions, GreenClean Corp., WasteGuard', status: false },
  { id: 22, name: 'Document Controller', assignedCompanies: 'FileTrack Inc., DocuManage, RecordsPro, DataArchive Solutions', status: true },
  { id: 23, name: 'Mechanical Engineer', assignedCompanies: 'MechPro Corp., Engineering Solutions, Design Works, TechFab Inc.', status: true },
  { id: 24, name: 'Security Officer', assignedCompanies: 'GuardForce, SecureZone, ProtectFirst, Vigilance Corp., SafeAccess', status: true },
  { id: 25, name: 'Shipping Clerk', assignedCompanies: 'PackRight, ShipFast Inc., Cargo Express, Dispatch Solutions', status: true },
];

export const MOCK_ARCHIVED_JOB_ROLES: JobRole[] = [
  { id: 101, name: 'Innovative Waste Management Techniques', assignedCompanies: '', status: false, archivedAt: new Date('2024-08-08T11:30:00') },
  { id: 102, name: 'Renewable Energy Initiatives', assignedCompanies: '', status: false, archivedAt: new Date('2024-08-09T13:00:00') },
  { id: 103, name: 'Smart Agriculture Technologies', assignedCompanies: '', status: false, archivedAt: new Date('2024-08-12T14:15:00') },
  { id: 104, name: 'Eco-Friendly Transportation Solutions', assignedCompanies: '', status: false, archivedAt: new Date('2024-08-13T15:45:00') },
  { id: 105, name: 'Circular Economy Practices', assignedCompanies: '', status: false, archivedAt: new Date('2024-08-14T09:30:00') },
  { id: 106, name: 'Green Building Standards', assignedCompanies: '', status: false, archivedAt: new Date('2024-08-15T10:45:00') },
  { id: 107, name: 'Water Conservation Technologies', assignedCompanies: '', status: false, archivedAt: new Date('2024-08-16T12:00:00') },
  { id: 108, name: 'Community Sustainability Programs', assignedCompanies: '', status: false, archivedAt: new Date('2024-08-19T13:15:00') },
  { id: 109, name: 'Environmental Education Initiatives', assignedCompanies: '', status: false, archivedAt: new Date('2024-08-20T15:00:00') },
  { id: 110, name: 'Carbon Footprint Reduction Program', assignedCompanies: '', status: false, archivedAt: new Date('2024-08-21T10:00:00') },
  { id: 111, name: 'Sustainable Supply Chain Management', assignedCompanies: '', status: false, archivedAt: new Date('2024-08-22T11:30:00') },
  { id: 112, name: 'Green IT Infrastructure', assignedCompanies: '', status: false, archivedAt: new Date('2024-08-23T09:00:00') },
  { id: 113, name: 'Eco-Conscious Manufacturing', assignedCompanies: '', status: false, archivedAt: new Date('2024-08-26T14:00:00') },
  { id: 114, name: 'Biodiversity Conservation Specialist', assignedCompanies: '', status: false, archivedAt: new Date('2024-08-27T10:30:00') },
  { id: 115, name: 'Climate Change Adaptation Planner', assignedCompanies: '', status: false, archivedAt: new Date('2024-08-28T15:00:00') },
  { id: 116, name: 'Zero Waste Program Coordinator', assignedCompanies: '', status: false, archivedAt: new Date('2024-08-29T09:30:00') },
  { id: 117, name: 'Renewable Materials Researcher', assignedCompanies: '', status: false, archivedAt: new Date('2024-08-30T12:00:00') },
  { id: 118, name: 'Urban Sustainability Consultant', assignedCompanies: '', status: false, archivedAt: new Date('2024-09-02T10:00:00') },
  { id: 119, name: 'Green Procurement Officer', assignedCompanies: '', status: false, archivedAt: new Date('2024-09-03T11:15:00') },
  { id: 120, name: 'Environmental Impact Assessor', assignedCompanies: '', status: false, archivedAt: new Date('2024-09-04T14:30:00') },
  { id: 121, name: 'Sustainable Energy Auditor', assignedCompanies: '', status: false, archivedAt: new Date('2024-09-05T09:00:00') },
  { id: 122, name: 'Organic Farming Practices Lead', assignedCompanies: '', status: false, archivedAt: new Date('2024-09-06T13:00:00') },
];
