import type { Article, ArchivedArticle, SiteArticle, CompanyArticle, ArchivedCategory, ActiveCategory } from '@/types/policies';

export const MOCK_ARTICLES: Article[] = [
  { id: 1, name: 'Employee Handbook', articleType: 'Company', category: 'Code of Conduct', hasDragHandle: true },
  { id: 1, name: 'Staff User Regulations', articleType: 'Site', category: 'Onboarding', hasDragHandle: false },
  { id: 2, name: 'Environmental Policy', articleType: 'Master', category: 'Data Protection Measures', hasDragHandle: true },
  { id: 3, name: 'Emergency Protocols', articleType: 'Company', category: 'Crisis Response Plan', hasDragHandle: true },
  { id: 4, name: 'Training Manual', articleType: 'Company', category: 'Onboarding Procedures', hasDragHandle: true },
  { id: 5, name: 'Remote Work Guidelines', articleType: 'Master', category: 'Home Office Standards', hasDragHandle: true },
  { id: 6, name: 'Environmental Policy', articleType: 'Company', category: 'Sustainability Practices', hasDragHandle: true },
  { id: 7, name: 'Incident Report Form', articleType: 'Company', category: 'Accident Reporting Procedures', hasDragHandle: true },
  { id: 8, name: 'Quality Assurance Manual', articleType: 'Company', category: 'Product Standards', hasDragHandle: true },
  { id: 9, name: 'IT Security Policies', articleType: 'Company', category: 'Data Protection Measures', hasDragHandle: true },
  { id: 10, name: 'Diversity & Inclusion Policy', articleType: 'Company', category: 'Equity Practices', hasDragHandle: true },
  { id: 11, name: 'WHS Policy', articleType: 'Site', category: 'Hazard & Risk Management', hasDragHandle: false },
  { id: 12, name: 'Anti-Harassment Policy', articleType: 'Master', category: 'Code of Conduct', hasDragHandle: true },
  { id: 13, name: 'Leave Entitlements Guide', articleType: 'Company', category: 'HR Policies', hasDragHandle: true },
  { id: 14, name: 'Contractor Safety Induction', articleType: 'Company', category: 'Safety Compliance', hasDragHandle: true },
  { id: 15, name: 'Drug & Alcohol Policy', articleType: 'Site', category: 'Workplace Safety', hasDragHandle: false },
  { id: 16, name: 'Vehicle Use Policy', articleType: 'Company', category: 'Fleet Management', hasDragHandle: true },
  { id: 17, name: 'Whistleblower Protection', articleType: 'Master', category: 'Legal Compliance', hasDragHandle: true },
  { id: 18, name: 'Workplace Bullying Policy', articleType: 'Company', category: 'Code of Conduct', hasDragHandle: true },
  { id: 19, name: 'First Aid Procedures', articleType: 'Site', category: 'Emergency Response', hasDragHandle: false },
  { id: 20, name: 'Manual Handling Guide', articleType: 'Company', category: 'Safety Compliance', hasDragHandle: true },
];

export const MOCK_ARCHIVED_ARTICLES: ArchivedArticle[] = [
  { id: 2, name: 'Safety Procedures', category: 'Incident Reporting Guidelines', hasDragHandle: true },
  { id: 3, name: 'Employee Training', category: 'Safety Awareness Programs', hasDragHandle: true },
  { id: 4, name: 'Equipment Safety', category: 'Machinery Operation Standards', hasDragHandle: true },
  { id: 5, name: 'Emergency Procedures', category: 'Evacuation Plans', hasDragHandle: true },
  { id: 6, name: 'Health Policies', category: 'Workplace Health Initiatives', hasDragHandle: true },
  { id: 7, name: 'Compliance Standards', category: 'Regulatory Requirements', hasDragHandle: true },
  { id: 8, name: 'Reporting Protocols', category: 'Accident Reporting Procedures', hasDragHandle: true },
  { id: 9, name: 'Incident Investigation', category: 'Root Cause Analysis', hasDragHandle: true },
  { id: 10, name: 'Personal Protective Equipment', category: 'Usage Guidelines', hasDragHandle: true },
  { id: 11, name: 'Workplace Ergonomics', category: 'Safe Work Practices', hasDragHandle: true },
  { id: 12, name: 'Fire Safety Manual', category: 'Emergency Response', hasDragHandle: true },
  { id: 13, name: 'Chemical Handling Guide', category: 'Hazardous Materials', hasDragHandle: true },
  { id: 14, name: 'Noise Control Policy', category: 'Workplace Health Initiatives', hasDragHandle: true },
  { id: 15, name: 'Confined Space Entry', category: 'Safety Compliance', hasDragHandle: true },
  { id: 16, name: 'Electrical Safety Standards', category: 'Regulatory Requirements', hasDragHandle: true },
  { id: 17, name: 'Fall Prevention Policy', category: 'Hazard & Risk Management', hasDragHandle: true },
  { id: 18, name: 'Forklift Operation Manual', category: 'Machinery Operation Standards', hasDragHandle: true },
  { id: 19, name: 'Heat Stress Management', category: 'Workplace Health Initiatives', hasDragHandle: true },
  { id: 20, name: 'Lockout Tagout Procedures', category: 'Safety Compliance', hasDragHandle: true },
  { id: 21, name: 'Manual Tasks Risk Assessment', category: 'Root Cause Analysis', hasDragHandle: true },
  { id: 22, name: 'Respiratory Protection Policy', category: 'Usage Guidelines', hasDragHandle: true },
  { id: 23, name: 'Scaffolding Safety Guide', category: 'Hazard & Risk Management', hasDragHandle: true },
  { id: 24, name: 'Sharps Disposal Protocol', category: 'Hazardous Materials', hasDragHandle: true },
  { id: 25, name: 'Spill Response Procedure', category: 'Emergency Response', hasDragHandle: true },
  { id: 26, name: 'Traffic Management Plan', category: 'Safe Work Practices', hasDragHandle: true },
  { id: 27, name: 'Vibration Exposure Policy', category: 'Workplace Health Initiatives', hasDragHandle: true },
  { id: 28, name: 'Welding Safety Standards', category: 'Machinery Operation Standards', hasDragHandle: true },
  { id: 29, name: 'Working at Heights Policy', category: 'Hazard & Risk Management', hasDragHandle: true },
  { id: 30, name: 'Asbestos Management Plan', category: 'Hazardous Materials', hasDragHandle: true },
  { id: 31, name: 'Contractor Induction Pack', category: 'Safety Awareness Programs', hasDragHandle: true },
  { id: 32, name: 'Dangerous Goods Storage', category: 'Regulatory Requirements', hasDragHandle: true },
  { id: 33, name: 'Demolition Safety Guide', category: 'Safety Compliance', hasDragHandle: true },
  { id: 34, name: 'Dust Control Measures', category: 'Workplace Health Initiatives', hasDragHandle: true },
  { id: 35, name: 'Excavation Safety Plan', category: 'Hazard & Risk Management', hasDragHandle: true },
  { id: 36, name: 'Eye Protection Standards', category: 'Usage Guidelines', hasDragHandle: true },
  { id: 37, name: 'Fatigue Management Policy', category: 'Safe Work Practices', hasDragHandle: true },
  { id: 38, name: 'Gas Detection Procedures', category: 'Emergency Response', hasDragHandle: true },
  { id: 39, name: 'Hazard Identification Guide', category: 'Root Cause Analysis', hasDragHandle: true },
  { id: 40, name: 'Lone Worker Safety Policy', category: 'Incident Reporting Guidelines', hasDragHandle: true },
  { id: 41, name: 'Overhead Crane Operations', category: 'Machinery Operation Standards', hasDragHandle: true },
  { id: 42, name: 'Permit to Work System', category: 'Safety Compliance', hasDragHandle: true },
  { id: 43, name: 'Plant & Equipment Register', category: 'Regulatory Requirements', hasDragHandle: true },
  { id: 44, name: 'Risk Assessment Template', category: 'Root Cause Analysis', hasDragHandle: true },
  { id: 45, name: 'Safe Work Method Statement', category: 'Safe Work Practices', hasDragHandle: true },
  { id: 46, name: 'Silica Dust Exposure Policy', category: 'Hazardous Materials', hasDragHandle: true },
  { id: 47, name: 'Tool Safety Inspection Guide', category: 'Machinery Operation Standards', hasDragHandle: true },
  { id: 48, name: 'UV Exposure Protection', category: 'Workplace Health Initiatives', hasDragHandle: true },
  { id: 49, name: 'Vehicle Inspection Checklist', category: 'Incident Reporting Guidelines', hasDragHandle: true },
  { id: 50, name: 'Waste Disposal Guidelines', category: 'Hazardous Materials', hasDragHandle: true },
  { id: 51, name: 'Water Safety Management', category: 'Emergency Response', hasDragHandle: true },
  { id: 52, name: 'Workplace Violence Policy', category: 'Incident Reporting Guidelines', hasDragHandle: true },
  { id: 53, name: 'X-Ray Safety Procedures', category: 'Usage Guidelines', hasDragHandle: true },
  { id: 54, name: 'Yard Safety Operations', category: 'Safe Work Practices', hasDragHandle: true },
  { id: 55, name: 'Zero Harm Framework', category: 'Safety Awareness Programs', hasDragHandle: true },
  { id: 56, name: 'Accident Investigation Form', category: 'Root Cause Analysis', hasDragHandle: true },
  { id: 57, name: 'Building Evacuation Plan', category: 'Evacuation Plans', hasDragHandle: true },
  { id: 58, name: 'Compliance Audit Checklist', category: 'Regulatory Requirements', hasDragHandle: true },
  { id: 59, name: 'Driver Safety Handbook', category: 'Safe Work Practices', hasDragHandle: true },
  { id: 60, name: 'Environmental Impact Policy', category: 'Hazardous Materials', hasDragHandle: true },
  { id: 61, name: 'First Aid Kit Inspection', category: 'Emergency Response', hasDragHandle: true },
  { id: 62, name: 'Grinder Safety Protocol', category: 'Machinery Operation Standards', hasDragHandle: true },
  { id: 63, name: 'Hearing Conservation Program', category: 'Workplace Health Initiatives', hasDragHandle: true },
  { id: 64, name: 'Isolation Procedure Guide', category: 'Safety Compliance', hasDragHandle: true },
  { id: 65, name: 'Job Safety Analysis Template', category: 'Hazard & Risk Management', hasDragHandle: true },
  { id: 66, name: 'Knife Safety Guidelines', category: 'Usage Guidelines', hasDragHandle: true },
  { id: 67, name: 'Laser Safety Standards', category: 'Regulatory Requirements', hasDragHandle: true },
  { id: 68, name: 'Mobile Plant Operations', category: 'Machinery Operation Standards', hasDragHandle: true },
  { id: 69, name: 'Night Shift Safety Policy', category: 'Safe Work Practices', hasDragHandle: true },
  { id: 70, name: 'Occupational Hygiene Guide', category: 'Workplace Health Initiatives', hasDragHandle: true },
  { id: 71, name: 'Pressure Vessel Safety', category: 'Safety Compliance', hasDragHandle: true },
  { id: 72, name: 'Quality Control Procedures', category: 'Regulatory Requirements', hasDragHandle: true },
  { id: 73, name: 'Radiation Safety Manual', category: 'Hazardous Materials', hasDragHandle: true },
  { id: 74, name: 'Sling & Rigging Safety', category: 'Hazard & Risk Management', hasDragHandle: true },
  { id: 75, name: 'Toolbox Talk Templates', category: 'Safety Awareness Programs', hasDragHandle: true },
  { id: 76, name: 'Underground Mining Safety', category: 'Safety Compliance', hasDragHandle: true },
  { id: 77, name: 'Ventilation Assessment Guide', category: 'Workplace Health Initiatives', hasDragHandle: true },
  { id: 78, name: 'Warehouse Safety Standards', category: 'Safe Work Practices', hasDragHandle: true },
  { id: 79, name: 'Workshop Safety Rules', category: 'Machinery Operation Standards', hasDragHandle: true },
  { id: 80, name: 'Yard Hazard Assessment', category: 'Hazard & Risk Management', hasDragHandle: true },
  { id: 81, name: 'Zone Classification Guide', category: 'Regulatory Requirements', hasDragHandle: true },
  { id: 82, name: 'Aerial Work Platform Safety', category: 'Hazard & Risk Management', hasDragHandle: true },
  { id: 83, name: 'Biological Hazard Protocol', category: 'Hazardous Materials', hasDragHandle: true },
  { id: 84, name: 'Crane Lift Planning Guide', category: 'Machinery Operation Standards', hasDragHandle: true },
  { id: 85, name: 'Decontamination Procedures', category: 'Emergency Response', hasDragHandle: true },
  { id: 86, name: 'Emergency Warden Training', category: 'Evacuation Plans', hasDragHandle: true },
  { id: 87, name: 'Flood Response Protocol', category: 'Emergency Response', hasDragHandle: true },
  { id: 88, name: 'Ground Disturbance Permit', category: 'Safety Compliance', hasDragHandle: true },
  { id: 89, name: 'Hazmat Transport Guide', category: 'Hazardous Materials', hasDragHandle: true },
  { id: 90, name: 'Incident Notification Policy', category: 'Incident Reporting Guidelines', hasDragHandle: true },
];

export const MOCK_SITE_ARTICLES: SiteArticle[] = [
  { id: 2, name: 'Safety Regulations', site: 'Queensland, Brisbane, Gold Coast, Cairns', category: 'Occupational Health & Safety', isActive: false },
  { id: 3, name: 'Emergency Procedures', site: 'New South Wales, Sydney, Newcastle, Wollongong', category: 'Crisis Management', isActive: true },
  { id: 4, name: 'Training Requirements', site: 'Victoria, Geelong, Ballarat, Bendigo', category: 'Employee Training', isActive: false },
  { id: 5, name: 'Incident Reporting', site: 'Western Australia, Perth, Mandurah, Albany', category: 'Reporting Procedures', isActive: true },
  { id: 6, name: 'Workplace Safety', site: 'South Australia, Adelaide, Mount Gambier, Whyalla', category: 'Safe Work Practices', isActive: false },
  { id: 7, name: 'Safety Audits', site: 'Tasmania, Hobart, Launceston, Devonport', category: 'Audit Procedures', isActive: true },
  { id: 8, name: 'Environmental Policies', site: 'Northern Territory, Darwin, Alice Springs, Katherine', category: 'Sustainability Practices', isActive: false },
  { id: 9, name: 'Workplace Health', site: 'Australian Capital Territory, Canberra', category: 'Health Promotion', isActive: false },
  { id: 10, name: 'Compliance Monitoring', site: 'Tasmania, Hobart, Launceston, Devonport', category: 'Compliance Checks', isActive: false },
  { id: 11, name: 'Employee Wellbeing', site: 'South Australia, Adelaide, Mount Gambier, Whyalla', category: 'Wellbeing Initiatives', isActive: false },
  { id: 12, name: 'Safety Equipment', site: 'New South Wales, Sydney, Newcastle, Wollongong', category: 'Equipment Standards', isActive: false },
  { id: 13, name: 'Risk Assessment Guide', site: 'Queensland, Brisbane, Gold Coast, Cairns', category: 'Hazard & Risk Management', isActive: true },
  { id: 14, name: 'Fire Safety Protocol', site: 'Victoria, Melbourne, Geelong, Ballarat', category: 'Emergency Response', isActive: false },
  { id: 15, name: 'Chemical Handling', site: 'Western Australia, Perth, Bunbury, Geraldton', category: 'Hazardous Materials', isActive: true },
  { id: 16, name: 'Confined Space Entry', site: 'New South Wales, Sydney, Wollongong, Newcastle', category: 'Safety Compliance', isActive: false },
  { id: 17, name: 'Noise Control Standards', site: 'South Australia, Adelaide, Port Augusta', category: 'Workplace Health', isActive: false },
  { id: 18, name: 'Fall Protection Policy', site: 'Queensland, Townsville, Mackay, Rockhampton', category: 'Hazard & Risk Management', isActive: true },
  { id: 19, name: 'Manual Handling Guide', site: 'Victoria, Bendigo, Shepparton, Mildura', category: 'Safe Work Practices', isActive: false },
  { id: 20, name: 'Electrical Safety', site: 'Tasmania, Hobart, Launceston, Burnie', category: 'Regulatory Requirements', isActive: false },
  { id: 21, name: 'Dust Control Measures', site: 'Northern Territory, Darwin, Alice Springs', category: 'Environmental Compliance', isActive: true },
  { id: 22, name: 'PPE Usage Guide', site: 'Western Australia, Perth, Kalgoorlie, Broome', category: 'Usage Guidelines', isActive: false },
  { id: 23, name: 'Scaffolding Safety', site: 'New South Wales, Newcastle, Central Coast', category: 'Construction Safety', isActive: false },
  { id: 24, name: 'Forklift Operations', site: 'Queensland, Brisbane, Logan, Ipswich', category: 'Machinery Operation', isActive: true },
  { id: 25, name: 'Heat Stress Management', site: 'Northern Territory, Darwin, Katherine', category: 'Workplace Health', isActive: false },
  { id: 26, name: 'Lockout Tagout', site: 'Victoria, Melbourne, Dandenong, Frankston', category: 'Safety Compliance', isActive: false },
  { id: 27, name: 'Spill Response Plan', site: 'South Australia, Adelaide, Whyalla', category: 'Emergency Response', isActive: true },
  { id: 28, name: 'Crane Operations', site: 'Western Australia, Perth, Fremantle', category: 'Machinery Operation', isActive: false },
  { id: 29, name: 'Welding Safety', site: 'Queensland, Cairns, Townsville', category: 'Equipment Standards', isActive: false },
  { id: 30, name: 'Working at Heights', site: 'New South Wales, Sydney, Parramatta', category: 'Hazard & Risk Management', isActive: true },
  { id: 31, name: 'Asbestos Management', site: 'Tasmania, Hobart, Devonport', category: 'Hazardous Materials', isActive: false },
];

export const MOCK_COMPANY_ARTICLES: CompanyArticle[] = [
  { id: 3, name: 'Annual Overview', category: 'FINANCIAL PERFORMANCE', reviewDate: 'August, 15, 2025 10:30 AM', isActive: false },
  { id: 4, name: 'Monthly Update', category: 'PROJECT STATUS', reviewDate: 'September, 5, 2025 11:00 AM', isActive: false },
  { id: 5, name: 'Weekly Briefing', category: 'TEAM PROGRESS', reviewDate: 'October, 2, 2025 2:00 PM', isActive: true },
  { id: 6, name: 'Special Session', category: 'MARKETING STRATEGY', reviewDate: 'November, 10, 2025 1:15 PM', isActive: false },
  { id: 7, name: 'Executive Summary', category: 'HR INITIATIVES', reviewDate: 'December, 3, 2025 3:45 PM', isActive: true },
  { id: 8, name: 'Performance Review', category: 'SALES ANALYSIS', reviewDate: 'January, 12, 2026 9:30 AM', isActive: false },
  { id: 9, name: 'Budget Discussion', category: 'FINANCIAL PLANNING', reviewDate: 'February, 8, 2026 4:00 PM', isActive: false },
  { id: 10, name: 'Innovation Forum', category: 'PRODUCT DEVELOPMENT', reviewDate: 'March, 20, 2026 12:00 PM', isActive: false },
  { id: 11, name: 'Strategy Workshop', category: 'COMPETITIVE ANALYSIS', reviewDate: 'April, 11, 2026 10:00 AM', isActive: false },
  { id: 12, name: 'Feedback Session', category: 'CLIENT RELATIONS', reviewDate: 'May, 25, 2026 2:30 PM', isActive: false },
  { id: 13, name: 'Quarterly Report', category: 'REVENUE TRACKING', reviewDate: 'June, 14, 2025 9:00 AM', isActive: true },
  { id: 14, name: 'Risk Assessment', category: 'COMPLIANCE REVIEW', reviewDate: 'July, 22, 2025 11:30 AM', isActive: false },
  { id: 15, name: 'Training Handbook', category: 'EMPLOYEE DEVELOPMENT', reviewDate: 'August, 30, 2025 3:00 PM', isActive: false },
  { id: 16, name: 'Safety Guidelines', category: 'WORKPLACE STANDARDS', reviewDate: 'September, 18, 2025 10:45 AM', isActive: true },
  { id: 17, name: 'Policy Manual', category: 'GOVERNANCE FRAMEWORK', reviewDate: 'October, 7, 2025 1:00 PM', isActive: false },
  { id: 18, name: 'Onboarding Pack', category: 'NEW HIRE RESOURCES', reviewDate: 'November, 25, 2025 9:15 AM', isActive: false },
  { id: 19, name: 'Vendor Agreement', category: 'PROCUREMENT STANDARDS', reviewDate: 'December, 15, 2025 2:45 PM', isActive: true },
  { id: 20, name: 'IT Security Guide', category: 'DATA PROTECTION', reviewDate: 'January, 28, 2026 11:00 AM', isActive: false },
  { id: 21, name: 'Brand Standards', category: 'MARKETING GUIDELINES', reviewDate: 'February, 19, 2026 10:30 AM', isActive: false },
  { id: 22, name: 'Travel Policy', category: 'EXPENSE MANAGEMENT', reviewDate: 'March, 8, 2026 3:30 PM', isActive: false },
  { id: 23, name: 'Code of Conduct', category: 'ETHICS STANDARDS', reviewDate: 'April, 2, 2026 9:00 AM', isActive: true },
  { id: 24, name: 'Leave Entitlements', category: 'HR POLICIES', reviewDate: 'May, 16, 2026 1:45 PM', isActive: false },
  { id: 25, name: 'Fleet Management', category: 'VEHICLE STANDARDS', reviewDate: 'June, 30, 2025 10:00 AM', isActive: false },
  { id: 26, name: 'Environmental Plan', category: 'SUSTAINABILITY GOALS', reviewDate: 'July, 12, 2025 2:00 PM', isActive: true },
  { id: 27, name: 'Crisis Response', category: 'EMERGENCY PROTOCOLS', reviewDate: 'August, 5, 2025 11:15 AM', isActive: false },
  { id: 28, name: 'Quality Assurance', category: 'PRODUCT STANDARDS', reviewDate: 'September, 22, 2025 4:30 PM', isActive: false },
  { id: 29, name: 'Diversity Policy', category: 'INCLUSION PRACTICES', reviewDate: 'October, 14, 2025 9:45 AM', isActive: false },
  { id: 30, name: 'Whistleblower Guide', category: 'LEGAL COMPLIANCE', reviewDate: 'November, 3, 2025 12:30 PM', isActive: true },
];

export const MOCK_ARCHIVED_CATEGORIES: ArchivedCategory[] = [
  { id: 1, name: 'WHS Policy', dateDeleted: 'July 09, 2025    10:05 AM', isActive: true, hasDragHandle: true },
  { id: 2, name: 'Data Protection Policy', dateDeleted: 'August 15, 2025    11:30 AM', isActive: false, hasDragHandle: true },
  { id: 3, name: 'Code of Conduct', dateDeleted: 'September 20, 2025    02:00 PM', isActive: false, hasDragHandle: true },
  { id: 4, name: 'Remote Work Guidelines', dateDeleted: 'October 01, 2025    09:45 AM', isActive: true, hasDragHandle: true },
  { id: 5, name: 'Harassment Prevention Policy', dateDeleted: 'October 15, 2025    01:15 PM', isActive: true, hasDragHandle: true },
  { id: 6, name: 'Diversity and Inclusion Policy', dateDeleted: 'November 10, 2025    03:00 PM', isActive: false, hasDragHandle: true },
  { id: 7, name: 'Health and Safety Procedures', dateDeleted: 'December 01, 2025    10:30 AM', isActive: false, hasDragHandle: true },
  { id: 8, name: 'Sustainability Initiatives', dateDeleted: 'January 25, 2026    12:00 PM', isActive: false, hasDragHandle: true },
  { id: 9, name: 'Employee Training Program', dateDeleted: 'February 05, 2026    04:30 PM', isActive: false, hasDragHandle: true },
  { id: 10, name: 'Anti-Bribery Standards', dateDeleted: 'March 12, 2026    09:00 AM', isActive: false, hasDragHandle: true },
  { id: 11, name: 'Incident Reporting Framework', dateDeleted: 'April 03, 2025    02:15 PM', isActive: true, hasDragHandle: true },
  { id: 12, name: 'Quality Management System', dateDeleted: 'May 18, 2025    11:45 AM', isActive: false, hasDragHandle: true },
  { id: 13, name: 'Environmental Compliance', dateDeleted: 'June 07, 2025    03:30 PM', isActive: false, hasDragHandle: true },
  { id: 14, name: 'Contractor Management', dateDeleted: 'July 22, 2025    10:00 AM', isActive: true, hasDragHandle: true },
  { id: 15, name: 'Emergency Response Plan', dateDeleted: 'August 30, 2025    01:00 PM', isActive: false, hasDragHandle: true },
  { id: 16, name: 'Vehicle Use Standards', dateDeleted: 'September 14, 2025    08:30 AM', isActive: false, hasDragHandle: true },
  { id: 17, name: 'Fatigue Management', dateDeleted: 'October 28, 2025    04:00 PM', isActive: false, hasDragHandle: true },
  { id: 18, name: 'Noise Control Procedures', dateDeleted: 'November 19, 2025    09:15 AM', isActive: true, hasDragHandle: true },
  { id: 19, name: 'Chemical Safety Protocol', dateDeleted: 'December 10, 2025    02:30 PM', isActive: false, hasDragHandle: true },
  { id: 20, name: 'Manual Handling Policy', dateDeleted: 'January 05, 2026    11:00 AM', isActive: false, hasDragHandle: true },
  { id: 21, name: 'Fire Safety Standards', dateDeleted: 'February 17, 2026    10:45 AM', isActive: false, hasDragHandle: true },
  { id: 22, name: 'Electrical Safety Guide', dateDeleted: 'March 25, 2026    03:15 PM', isActive: true, hasDragHandle: true },
  { id: 23, name: 'Confined Space Entry', dateDeleted: 'April 08, 2025    09:30 AM', isActive: false, hasDragHandle: true },
  { id: 24, name: 'Fall Prevention Plan', dateDeleted: 'May 20, 2025    01:45 PM', isActive: false, hasDragHandle: true },
  { id: 25, name: 'PPE Usage Standards', dateDeleted: 'June 14, 2025    10:15 AM', isActive: false, hasDragHandle: true },
  { id: 26, name: 'Scaffolding Safety', dateDeleted: 'July 01, 2025    02:00 PM', isActive: true, hasDragHandle: true },
  { id: 27, name: 'Excavation Protocol', dateDeleted: 'August 19, 2025    08:45 AM', isActive: false, hasDragHandle: true },
  { id: 28, name: 'Working at Heights', dateDeleted: 'September 07, 2025    03:00 PM', isActive: false, hasDragHandle: true },
  { id: 29, name: 'Lockout Tagout Procedures', dateDeleted: 'October 23, 2025    11:30 AM', isActive: false, hasDragHandle: true },
  { id: 30, name: 'Dust Control Measures', dateDeleted: 'November 15, 2025    09:00 AM', isActive: true, hasDragHandle: true },
];

export const MOCK_ACTIVE_CATEGORIES: ActiveCategory[] = [
  { id: 2, name: 'Safety Regulations', categoryType: 'Company', hasDragHandle: true },
  { id: 3, name: 'Employee Handbook', categoryType: 'Site', hasDragHandle: true },
  { id: 4, name: 'Code of Conduct', categoryType: 'Company', hasDragHandle: true },
  { id: 5, name: 'Training Manual', categoryType: 'Company', hasDragHandle: true },
  { id: 6, name: 'Leave Policy', categoryType: 'Site', hasDragHandle: true },
  { id: 7, name: 'Compensation Overview', categoryType: 'Site', hasDragHandle: true },
  { id: 8, name: 'Diversity and Inclusion', categoryType: 'Company', hasDragHandle: true },
  { id: 9, name: 'Performance Review Process', categoryType: 'Company', hasDragHandle: true },
  { id: 10, name: 'IT Security Guidelines', categoryType: 'Company', hasDragHandle: true },
  { id: 11, name: 'Customer Service Standards', categoryType: 'Company', hasDragHandle: true },
  { id: 12, name: 'Environmental Policy', categoryType: 'Company', hasDragHandle: true },
  { id: 13, name: 'Workplace Health & Safety', categoryType: 'Site', hasDragHandle: true },
  { id: 14, name: 'Anti-Discrimination Policy', categoryType: 'Company', hasDragHandle: true },
  { id: 15, name: 'Remote Work Guidelines', categoryType: 'Company', hasDragHandle: true },
  { id: 16, name: 'Data Protection Standards', categoryType: 'Site', hasDragHandle: true },
  { id: 17, name: 'Quality Assurance', categoryType: 'Company', hasDragHandle: true },
  { id: 18, name: 'Incident Reporting', categoryType: 'Company', hasDragHandle: true },
  { id: 19, name: 'Emergency Procedures', categoryType: 'Site', hasDragHandle: true },
  { id: 20, name: 'Onboarding Checklist', categoryType: 'Company', hasDragHandle: true },
  { id: 21, name: 'Conflict Resolution', categoryType: 'Company', hasDragHandle: true },
  { id: 22, name: 'Travel Policy', categoryType: 'Company', hasDragHandle: true },
  { id: 23, name: 'Expense Management', categoryType: 'Site', hasDragHandle: true },
  { id: 24, name: 'Whistleblower Protection', categoryType: 'Company', hasDragHandle: true },
  { id: 25, name: 'Social Media Guidelines', categoryType: 'Company', hasDragHandle: true },
  { id: 26, name: 'Drug and Alcohol Policy', categoryType: 'Site', hasDragHandle: true },
  { id: 27, name: 'Grievance Handling', categoryType: 'Company', hasDragHandle: true },
  { id: 28, name: 'Attendance Policy', categoryType: 'Company', hasDragHandle: true },
  { id: 29, name: 'Contractor Management', categoryType: 'Site', hasDragHandle: true },
  { id: 30, name: 'Risk Assessment Framework', categoryType: 'Company', hasDragHandle: true },
];
